### ISSUE TITLE
Question: test suite metadata?

### ISSUE THREAD

**Issue by steve-bate** [ctrf-io/ctrf#1]
This effort looks like an interesting alternative to xUnit XML or TAP results capture.

I'm investigating how to use it with a custom test framework. This framework executes multiple test suites and I'd like to include metadata about each suite.  Is there a "standard" way to do that CTRF?

**Comment by Ma11hewThomas** [comment]
@steve-bate metadata is usually added to the [extra object](https://github.com/ctrf-io/ctrf/blob/main/docs/schema/extra.md), however, as CTRF uses a flat test structure, there isn't a property for suite of type object by which extra data can be added to. 

The best way to do this would be to generate a CTRF report for each suite and add the suite metadata to the [extra object](https://github.com/ctrf-io/ctrf/blob/main/docs/schema/extra.md) of the [results object](https://github.com/ctrf-io/ctrf/blob/main/docs/schema/results.md)
