### ISSUE TITLE
request: Support line information in Test object

### ISSUE THREAD

**Issue by an-ky** [ctrf-io/ctrf#7]
Several test frameworks are capable of reporting a full source location (file and line information of a failed test). 
Currently the Test object has a `filepath` attribute, line information need to be stored in the `extra` attribute. Would it be an option to add an optional `line` attribute to Test directly to formalize this a bit more.

**Comment by Ma11hewThomas** [comment]
Agreed, this is a sensible addition

As we are pre-major release of the schema, I'm happy to add optional fields right away. 

Implemented in #9
